version: '3.8'

services:
  transcribe:
    image: rocm/pytorch:rocm6.3_ubuntu22.04_py3.10_pytorch_release_2.3.0
    devices:
      - /dev/kfd
      - /dev/dri
    group_add:
      - video
    ipc: host
    shm_size: 16G
    volumes:
      - .:/workspace
      - $HOME/.cache:/root/.cache
    environment:
      - HSA_OVERRIDE_GFX_VERSION=11.0.0
      - PYTORCH_ROCM_ARCH=gfx1100
      - AMD_SERIALIZE_KERNEL=3
      - TORCH_USE_HIP_DSA=1
    working_dir: /workspace
    command: >
      bash -c "apt-get update && 
               apt-get install -y ffmpeg &&
               bash" 